spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookNest
    username: postgres #username
    password: 8475 #password

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: Suraj
    password: 8475
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectionTimeout: 5000
        timeout: 3000
        writeTimeOut: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      picture-output-path: ./uploads

server:
  port: 8090